on:
  push:
    branches:
      - master
      - popcorn-viewer

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - run: cd popcorn-viewer && npm install

      - run: cd popcorn-viewer && ./node_modules/.bin/parcel build index.html
